#!/usr/bin/env bash
# Resolves the build's CFBundleVersion (Apple-mandated monotonic int) and
# the short git SHA (for human-readable build display) and writes them into
# config/.local-version.xcconfig, which config/Version.xcconfig #include?s.
#
# Why both values:
#   CFBundleVersion must parse as a non-negative integer (App Store Connect
#   rejects strings). It is the "Apple-validated" build number.
#   GIT_SHA is dev-only — it never reaches CFBundleVersion — it just lets a
#   human tell two builds with the same int apart (dirty rebuild, CI retry).
#
# Source of BUILD_NUMBER, in order:
#   1. $BUILD_NUMBER env var (set by CI: GitHub Actions = $GITHUB_RUN_NUMBER,
#      Bitrise = $BITRISE_BUILD_NUMBER, etc.) — preferred, monotonic per run.
#   2. `git rev-list --count HEAD` — locally, monotonically grows with
#      commits; safe because the value is not uploaded to App Store from
#      a dev machine.
#   3. 0 — fallback for non-git, no-env environments (CI test containers).
#
# Idempotent: cmp -s skips the write when resolved values are unchanged,
# preserving mtime so Xcode's build cache stays valid across rapid rebuilds.
#
# Chained from `make build` (and `make compile-only`).

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$REPO_ROOT/config/.local-version.xcconfig"

# 1. Resolve BUILD_NUMBER (monotonic integer for CFBundleVersion).
if [[ -n "${BUILD_NUMBER:-}" ]]; then
  SOURCE="env"
elif git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
  BUILD_NUMBER="$(git -C "$REPO_ROOT" rev-list --count HEAD 2>/dev/null || echo 0)"
  SOURCE="git"
else
  BUILD_NUMBER="0"
  SOURCE="fallback"
fi

# 2. Resolve short SHA. -dirty suffix when there are uncommitted changes.
GIT_SHA=""
if git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
  FULL_SHA="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo)"
  if [[ -n "$FULL_SHA" ]]; then
    GIT_SHA="${FULL_SHA:0:7}"
    if ! git -C "$REPO_ROOT" diff --quiet HEAD 2>/dev/null; then
      GIT_SHA="${GIT_SHA}-dirty"
    fi
  fi
fi

TMP="$(mktemp "${OUT}.XXXXXX")"
cat > "$TMP" <<EOF
// Auto-generated by scripts/inject-build-timestamp.sh. Do not edit.
SMARTCHATAPP_BUILD_NUMBER = ${BUILD_NUMBER}
SMARTCHATAPP_GIT_SHA = ${GIT_SHA}
EOF

if [[ -f "$OUT" ]] && cmp -s "$TMP" "$OUT"; then
  rm -f "$TMP"
else
  mv "$TMP" "$OUT"
  echo "Wrote $OUT (build=${BUILD_NUMBER}, sha=${GIT_SHA:-none}, source=${SOURCE})"
fi
