#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="${ROOT_DIR}/config"
TEAM_ID_SCRIPT="${ROOT_DIR}/scripts/ios-team-id.sh"
LOCAL_SIGNING_FILE="${CONFIG_DIR}/.local-signing.xcconfig"

sanitize_identifier_segment() {
  local raw="${1:-}"
  raw="$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]')"
  raw="$(printf '%s' "$raw" | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/-+/-/g')"
  if [[ -z "$raw" ]]; then
    raw="local"
  fi
  printf '%s\n' "$raw"
}

normalize_bundle_id() {
  # Preserve case (CamelCase Bundle IDs like com.smartchat.SmartChatApp are valid).
  # Only normalize: collapse repeated dots, strip leading/trailing dots/dashes,
  # replace non-alnum/.-/runs with single dash.
  local raw="${1:-}"
  raw="$(printf '%s' "$raw" | sed -E 's/[^A-Za-z0-9.-]+/-/g; s/\.+/./g; s/^-+//; s/[.-]+$//')"
  if [[ -z "$raw" ]]; then
    raw="com.smartchat.app.test.local"
  fi
  printf '%s\n' "$raw"
}

if [[ ! -x "${TEAM_ID_SCRIPT}" ]]; then
  echo "ERROR: Missing team detection helper: ${TEAM_ID_SCRIPT}" >&2
  exit 1
fi

team_id=""
if team_id="$("${TEAM_ID_SCRIPT}" 2>/dev/null)"; then
  :
else
  if [[ "${IOS_SIGNING_REQUIRED:-0}" == "1" ]]; then
    "${TEAM_ID_SCRIPT}"
    exit 1
  fi

  echo "WARN: Unable to detect an Apple Team ID; keeping existing iOS signing override (if any)." >&2
  exit 0
fi

# Canonical Bundle IDs — for SmartChatApp we deliberately do NOT append
# a per-user suffix, to preserve upgrade continuity with the app already
# installed on devices. If multi-developer collision becomes an issue,
# re-introduce the suffix by setting SMARTCHATAPP_IOS_BUNDLE_SUFFIX.
if [[ -n "${SMARTCHATAPP_IOS_BUNDLE_SUFFIX:-}" ]]; then
  bundle_suffix="$(sanitize_identifier_segment "${SMARTCHATAPP_IOS_BUNDLE_SUFFIX}")"
  bundle_base="${SMARTCHATAPP_IOS_APP_BUNDLE_ID_BASE:-com.smartchat.SmartChatApp}"
  bundle_base="$(normalize_bundle_id "${bundle_base}.${bundle_suffix}")"
else
  bundle_base="${SMARTCHATAPP_IOS_APP_BUNDLE_ID:-com.smartchat.SmartChatApp}"
  bundle_base="$(normalize_bundle_id "${bundle_base}")"
fi

tests_bundle_id="${SMARTCHATAPP_IOS_TESTS_BUNDLE_ID:-${bundle_base}Tests}"
tests_bundle_id="$(normalize_bundle_id "${tests_bundle_id}")"

code_sign_style="${SMARTCHATAPP_IOS_CODE_SIGN_STYLE:-Automatic}"
app_profile="${SMARTCHATAPP_IOS_APP_PROFILE:-}"
tests_profile="${SMARTCHATAPP_IOS_TESTS_PROFILE:-}"

tmp_file="$(mktemp "${TMPDIR:-/tmp}/smartchatapp-ios-signing.XXXXXX")"
cat >"${tmp_file}" <<EOF
// Auto-generated by scripts/ios-configure-signing.sh.
// This file is local-only and should not be committed.
// Override values with env vars if needed:
// SMARTCHATAPP_IOS_APP_BUNDLE_ID / SMARTCHATAPP_IOS_TESTS_BUNDLE_ID
// SMARTCHATAPP_IOS_CODE_SIGN_STYLE / SMARTCHATAPP_IOS_APP_PROFILE
SMARTCHATAPP_CODE_SIGN_STYLE = ${code_sign_style}
SMARTCHATAPP_DEVELOPMENT_TEAM = ${team_id}
SMARTCHATAPP_IOS_SELECTED_TEAM = ${team_id}
SMARTCHATAPP_APP_BUNDLE_ID = ${bundle_base}
SMARTCHATAPP_TESTS_BUNDLE_ID = ${tests_bundle_id}
SMARTCHATAPP_APP_PROFILE = ${app_profile}
SMARTCHATAPP_TESTS_PROFILE = ${tests_profile}
EOF

if [[ -f "${LOCAL_SIGNING_FILE}" ]] && cmp -s "${tmp_file}" "${LOCAL_SIGNING_FILE}"; then
  rm -f "${tmp_file}"
  echo "iOS signing config already up to date: team=${team_id} app=${bundle_base}"
  exit 0
fi

mv "${tmp_file}" "${LOCAL_SIGNING_FILE}"
echo "Configured iOS signing: team=${team_id} app=${bundle_base}"
